name: Production CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  IMAGE_BACKEND: ghcr.io/sohailmukhtiar/backend-app
  IMAGE_FRONTEND: ghcr.io/sohailmukhtiar/frontend-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONARQUBE_URL }}

    - name: Check Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@v1
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Backend
      run: |
        docker build -t $IMAGE_BACKEND:$IMAGE_TAG Docker-Compose-Projects/backend
        docker push $IMAGE_BACKEND:$IMAGE_TAG

    - name: Build & Push Frontend
      run: |
        docker build -t $IMAGE_FRONTEND:$IMAGE_TAG Docker-Compose-Projects/frontend
        docker push $IMAGE_FRONTEND:$IMAGE_TAG

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u sohailmukhtiar --password-stdin
          cd ~/app
          docker compose -f docker-compose.deploy.yml pull
          docker compose -f docker-compose.deploy.yml up -d
